/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_itheima_cpphello_MainActivity */

#ifndef _Included_com_example_candcpp_MainActivity
#define _Included_com_example_candcpp_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_itheima_cpphello_MainActivity
 * Method:    helloFromCpp
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_candcpp_MainActivity_helloFromCpp
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
